In [5]:
import streamlit as st
import time
import numpy as np
import pandas as pd

In [2]:
st.set_page_config(page_title="PrÃªt Ã  dÃ©penser", page_icon="ðŸ’°")

st.markdown("# Plotting Demo")
st.sidebar.header("Demande de crÃ©dit")

2024-05-31 18:31:04.247
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Applications\Anaconda\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

DeltaGenerator(_root_container=1, _parent=DeltaGenerator())

In [63]:
def load_data() :
    # Load customers features as saved in .csv file thanks to a previous notebook
    clients = pd.read_csv("project/data/clients.csv", sep=";")
    
    # Use the line number as an ID for each customer
    clients['ID'] = clients.index
    
    # Move the ID column at 1st position in dataframe
    clients = clients[clients.columns.insert(0, 'ID')[:-1]]
    
    return clients

In [64]:
clients = load_data()

In [62]:
clients.head()

,ID,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,CODE_GENDER,DAYS_EMPLOYED,INSTAL_DPD_MAX,NAME_FAMILY_STATUS_Married,REFUSED_HOUR_APPR_PROCESS_START_MIN,PAYMENT_RATE,...,CC_CNT_INSTALMENT_MATURE_CUM_MEAN,PREV_CODE_REJECT_REASON_HC_MEAN,CLOSED_DAYS_CREDIT_ENDDATE_MAX,BURO_AMT_CREDIT_SUM_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,INSTAL_PAYMENT_DIFF_VAR,PREV_NAME_GOODS_CATEGORY_Mobile_MEAN,WEEKDAY_APPR_PROCESS_START_FRIDAY,PREV_AMT_ANNUITY_MAX,CC_MONTHS_BALANCE_VAR
0,0,0.159520,0.789654,0.752614,0.0,-2329.0,11.0,1.0,NaN,0.036147,...,NaN,0.0,-179.0,207623.571429,0.00,0.000000e+00,1.00,0.0,3951.000,NaN
1,1,0.432962,0.291656,0.564990,1.0,-4469.0,1.0,1.0,NaN,0.077973,...,NaN,0.0,-128.0,219042.000000,0.00,0.000000e+00,0.50,1.0,4813.200,NaN
2,2,0.610991,0.699787,NaN,1.0,-4458.0,21.0,1.0,NaN,0.105202,...,18.719101,0.0,-567.0,518070.015000,NaN,2.346772e+07,0.25,0.0,23153.985,776.000000
3,3,0.612704,0.509677,0.525734,0.0,-1866.0,7.0,1.0,NaN,0.031123,...,19.547619,0.0,-452.0,126739.590000,25347.69,2.972476e+06,0.20,0.0,11250.000,204.166667
4,4,NaN,0.425687,0.202145,1.0,-2191.0,0.0,1.0,NaN,0.051266,...,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.00,1.0,24463.710,NaN

In [39]:
colonnes = clients.columns.to_list()

In [ ]:
for c in colonnes : clients = clients[['ID'].append(colonnes)]

In [56]:
z=clients.columns.insert(0, 'ID')

In [59]:
z[:-1]

Index(['ID', 'ID', 'EXT_SOURCE_3', 'EXT_SOURCE_2', 'EXT_SOURCE_1',
       'CODE_GENDER', 'DAYS_EMPLOYED', 'INSTAL_DPD_MAX',
       'NAME_FAMILY_STATUS_Married', 'REFUSED_HOUR_APPR_PROCESS_START_MIN',
       ...
       'CC_CNT_INSTALMENT_MATURE_CUM_MEAN', 'PREV_CODE_REJECT_REASON_HC_MEAN',
       'CLOSED_DAYS_CREDIT_ENDDATE_MAX', 'BURO_AMT_CREDIT_SUM_MEAN',
       'ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN', 'INSTAL_PAYMENT_DIFF_VAR',
       'PREV_NAME_GOODS_CATEGORY_Mobile_MEAN',
       'WEEKDAY_APPR_PROCESS_START_FRIDAY', 'PREV_AMT_ANNUITY_MAX',
       'CC_MONTHS_BALANCE_VAR'],
      dtype='object', length=142)

,ID,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,CODE_GENDER,DAYS_EMPLOYED,INSTAL_DPD_MAX,NAME_FAMILY_STATUS_Married,REFUSED_HOUR_APPR_PROCESS_START_MIN,PAYMENT_RATE,...,PREV_CODE_REJECT_REASON_HC_MEAN,CLOSED_DAYS_CREDIT_ENDDATE_MAX,BURO_AMT_CREDIT_SUM_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,INSTAL_PAYMENT_DIFF_VAR,PREV_NAME_GOODS_CATEGORY_Mobile_MEAN,WEEKDAY_APPR_PROCESS_START_FRIDAY,PREV_AMT_ANNUITY_MAX,CC_MONTHS_BALANCE_VAR,ID
0,0,0.159520,0.789654,0.752614,0.0,-2329.0,11.0,1.0,NaN,0.036147,...,0.000,-179.0,2.076236e+05,0.0000,0.000000e+00,1.000,0.0,3951.000,NaN,0
1,1,0.432962,0.291656,0.564990,1.0,-4469.0,1.0,1.0,NaN,0.077973,...,0.000,-128.0,2.190420e+05,0.0000,0.000000e+00,0.500,1.0,4813.200,NaN,1
2,2,0.610991,0.699787,NaN,1.0,-4458.0,21.0,1.0,NaN,0.105202,...,0.000,-567.0,5.180700e+05,NaN,2.346772e+07,0.250,0.0,23153.985,776.000000,2
3,3,0.612704,0.509677,0.525734,0.0,-1866.0,7.0,1.0,NaN,0.031123,...,0.000,-452.0,1.267396e+05,25347.6900,2.972476e+06,0.200,0.0,11250.000,204.166667,3
4,4,NaN,0.425687,0.202145,1.0,-2191.0,0.0,1.0,NaN,0.051266,...,0.000,NaN,NaN,NaN,0.000000e+00,0.000,1.0,24463.710,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,48739,0.643026,0.648575,NaN,0.0,-5169.0,0.0,0.0,NaN,0.042354,...,0.000,-98.0,2.237598e+05,NaN,0.000000e+00,0.000,0.0,14222.430,NaN,48739
48740,48740,NaN,0.684596,NaN,0.0,-1149.0,19.0,1.0,NaN,0.051267,...,0.000,NaN,NaN,NaN,2.023069e+06,0.250,0.0,14571.765,NaN,48740
48741,48741,0.283712,0.632770,0.733503,0.0,-3037.0,0.0,1.0,NaN,0.105414,...,0.000,-13.0,4.312619e+05,29202.7500,0.000000e+00,0.500,0.0,15761.205,NaN,48741
48742,48742,0.595456,0.445701,0.373090,1.0,-2731.0,1.0,1.0,16.0,0.055840,...,0.400,-149.0,2.263932e+05,0.0000,0.000000e+00,0.200,0.0,23451.705,NaN,48742
48743,48743,0.272134,0.456541,NaN,0.0,-633.0,10.0,1.0,7.0,0.079003,...,0.125,-272.0,1.028820e+06,29134.1925,1.623749e+06,0.125,0.0,26474.625,13.000000,48743

In [45]:
colonnes

['ID',
 'EXT_SOURCE_3',
 'EXT_SOURCE_2',
 'EXT_SOURCE_1',
 'CODE_GENDER',
 'DAYS_EMPLOYED',
 'INSTAL_DPD_MAX',
 'NAME_FAMILY_STATUS_Married',
 'REFUSED_HOUR_APPR_PROCESS_START_MIN',
 'PAYMENT_RATE',
 'FLAG_OWN_CAR',
 'PREV_RATE_DOWN_PAYMENT_MAX',
 'POS_COUNT',
 'NAME_INCOME_TYPE_Working',
 'POS_SK_DPD_DEF_MAX',
 'ANNUITY_INCOME_PERC',
 'CC_CNT_DRAWINGS_CURRENT_VAR',
 'BURO_STATUS_X_MEAN_MEAN',
 'APPROVED_DAYS_DECISION_MIN',
 'BURO_CREDIT_ACTIVE_Closed_MEAN',
 'INSTAL_PAYMENT_PERC_SUM',
 'ACTIVE_DAYS_CREDIT_MAX',
 'FLAG_DOCUMENT_3',
 'APPROVED_CNT_PAYMENT_MEAN',
 'DAYS_EMPLOYED_PERC',
 'CNT_CHILDREN',
 'AMT_ANNUITY',
 'REGION_RATING_CLIENT',
 'OCCUPATION_TYPE_nan',
 'FLAG_PHONE',
 'REFUSED_APP_CREDIT_PERC_MIN',
 'PREV_CNT_PAYMENT_MEAN',
 'PREV_NAME_SELLER_INDUSTRY_Connectivity_MEAN',
 'PREV_NAME_TYPE_SUITE_Unaccompanied_MEAN',
 'POS_NAME_CONTRACT_STATUS_Active_MEAN',
 'APPROVED_AMT_DOWN_PAYMENT_MAX',
 'INSTAL_DAYS_ENTRY_PAYMENT_SUM',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'PREV_NAME_YIELD_GROUP_high_MEAN',
 'BURO_CREDIT_ACTIVE_Active_MEAN',
 'DAYS_ID_PUBLISH',
 'DAYS_LAST_PHONE_CHANGE',
 'NAME_CONTRACT_TYPE',
 'INSTAL_DPD_MEAN',
 'INSTAL_PAYMENT_DIFF_MEAN',
 'OWN_CAR_AGE',
 'PREV_APP_CREDIT_PERC_MIN',
 'INSTAL_PAYMENT_DIFF_SUM',
 'INSTAL_DBD_SUM',
 'PREV_NAME_CONTRACT_STATUS_Refused_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN',
 'APPROVED_APP_CREDIT_PERC_VAR',
 'PREV_APP_CREDIT_PERC_MEAN',
 'BURO_DAYS_CREDIT_MEAN',
 'INSTAL_AMT_PAYMENT_SUM',
 'PREV_APP_CREDIT_PERC_VAR',
 'PREV_NAME_CLIENT_TYPE_New_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_SUM',
 'APPROVED_RATE_DOWN_PAYMENT_MAX',
 'CLOSED_DAYS_CREDIT_MAX',
 'AMT_GOODS_PRICE',
 'CC_CNT_DRAWINGS_ATM_CURRENT_MEAN',
 'CC_CNT_DRAWINGS_CURRENT_MEAN',
 'BURO_AMT_CREDIT_MAX_OVERDUE_MEAN',
 'INSTAL_AMT_PAYMENT_MIN',
 'BURO_DAYS_CREDIT_VAR',
 'BURO_AMT_CREDIT_SUM_DEBT_MEAN',
 'POS_SK_DPD_DEF_MEAN',
 'CC_CNT_DRAWINGS_POS_CURRENT_VAR',
 'DAYS_BIRTH',
 'AMT_CREDIT',
 'ACTIVE_DAYS_CREDIT_ENDDATE_MAX',
 'CC_AMT_DRAWINGS_ATM_CURRENT_SUM',
 'REFUSED_CNT_PAYMENT_SUM',
 'REFUSED_APP_CREDIT_PERC_MEAN',
 'INSTAL_AMT_INSTALMENT_SUM',
 'APPROVED_RATE_DOWN_PAYMENT_MEAN',
 'BURO_DAYS_CREDIT_MAX',
 'PREV_NAME_TYPE_SUITE_Family_MEAN',
 'BURO_AMT_ANNUITY_MEAN',
 'PREV_AMT_ANNUITY_MEAN',
 'BURO_CREDIT_TYPE_Microloan_MEAN',
 'CC_CNT_DRAWINGS_CURRENT_SUM',
 'CC_AMT_PAYMENT_CURRENT_MEAN',
 'REFUSED_HOUR_APPR_PROCESS_START_MAX',
 'POS_MONTHS_BALANCE_MAX',
 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN',
 'INSTAL_PAYMENT_DIFF_MAX',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'APPROVED_APP_CREDIT_PERC_MAX',
 'NAME_INCOME_TYPE_Pensioner',
 'REGION_RATING_CLIENT_W_CITY',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'POS_NAME_CONTRACT_STATUS_Signed_MEAN',
 'ACTIVE_MONTHS_BALANCE_SIZE_MEAN',
 'APPROVED_AMT_ANNUITY_MAX',
 'INSTAL_AMT_PAYMENT_MEAN',
 'DAYS_REGISTRATION',
 'BURO_DAYS_CREDIT_ENDDATE_MAX',
 'INSTAL_NUM_INSTALMENT_VERSION_NUNIQUE',
 'BURO_AMT_CREDIT_SUM_SUM',
 'CNT_FAM_MEMBERS',
 'REFUSED_AMT_CREDIT_MIN',
 'INSTAL_DAYS_ENTRY_PAYMENT_MEAN',
 'CC_AMT_DRAWINGS_ATM_CURRENT_VAR',
 'ACTIVE_AMT_CREDIT_SUM_MEAN',
 'PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN',
 'PREV_NAME_YIELD_GROUP_low_action_MEAN',
 'CC_CNT_DRAWINGS_CURRENT_MAX',
 'PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN',
 'HOUR_APPR_PROCESS_START',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'BURO_STATUS_1_MEAN_MEAN',
 'INSTAL_DPD_SUM',
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MAX',
 'REFUSED_CNT_PAYMENT_MEAN',
 'REG_CITY_NOT_WORK_CITY',
 'CC_AMT_BALANCE_MIN',
 'PREV_NAME_YIELD_GROUP_middle_MEAN',
 'APPROVED_AMT_DOWN_PAYMENT_MIN',
 'CC_AMT_CREDIT_LIMIT_ACTUAL_MEAN',
 'CLOSED_AMT_CREDIT_SUM_MEAN',
 'YEARS_BEGINEXPLUATATION_MODE',
 'WALLSMATERIAL_MODE_Panel',
 'INSTAL_AMT_INSTALMENT_MAX',
 'APPROVED_HOUR_APPR_PROCESS_START_MAX',
 'BURO_DAYS_CREDIT_MIN',
 'PREV_AMT_DOWN_PAYMENT_MAX',
 'APPROVED_APP_CREDIT_PERC_MEAN',
 'INSTAL_PAYMENT_PERC_MEAN',
 'CLOSED_AMT_CREDIT_SUM_SUM',
 'CC_CNT_INSTALMENT_MATURE_CUM_MEAN',
 'PREV_CODE_REJECT_REASON_HC_MEAN',
 'CLOSED_DAYS_CREDIT_ENDDATE_MAX',
 'BURO_AMT_CREDIT_SUM_MEAN',
 'ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN',
 'INSTAL_PAYMENT_DIFF_VAR',
 'PREV_NAME_GOODS_CATEGORY_Mobile_MEAN',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'PREV_AMT_ANNUITY_MAX',
 'CC_MONTHS_BALANCE_VAR']

In [42]:
z='ID'
z.append(colonnes)
z

AttributeError: 'str' object has no attribute 'append'

In [31]:
clients[z]

TypeError: unhashable type: 'Index'

In [29]:
type(z)

list

In [11]:
clients.head()

,EXT_SOURCE_3,EXT_SOURCE_2,EXT_SOURCE_1,CODE_GENDER,DAYS_EMPLOYED,INSTAL_DPD_MAX,NAME_FAMILY_STATUS_Married,REFUSED_HOUR_APPR_PROCESS_START_MIN,PAYMENT_RATE,FLAG_OWN_CAR,...,PREV_CODE_REJECT_REASON_HC_MEAN,CLOSED_DAYS_CREDIT_ENDDATE_MAX,BURO_AMT_CREDIT_SUM_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,INSTAL_PAYMENT_DIFF_VAR,PREV_NAME_GOODS_CATEGORY_Mobile_MEAN,WEEKDAY_APPR_PROCESS_START_FRIDAY,PREV_AMT_ANNUITY_MAX,CC_MONTHS_BALANCE_VAR,ID
0,0.159520,0.789654,0.752614,0.0,-2329.0,11.0,1.0,NaN,0.036147,0.0,...,0.0,-179.0,207623.571429,0.00,0.000000e+00,1.00,0.0,3951.000,NaN,0
1,0.432962,0.291656,0.564990,1.0,-4469.0,1.0,1.0,NaN,0.077973,0.0,...,0.0,-128.0,219042.000000,0.00,0.000000e+00,0.50,1.0,4813.200,NaN,1
2,0.610991,0.699787,NaN,1.0,-4458.0,21.0,1.0,NaN,0.105202,1.0,...,0.0,-567.0,518070.015000,NaN,2.346772e+07,0.25,0.0,23153.985,776.000000,2
3,0.612704,0.509677,0.525734,0.0,-1866.0,7.0,1.0,NaN,0.031123,0.0,...,0.0,-452.0,126739.590000,25347.69,2.972476e+06,0.20,0.0,11250.000,204.166667,3
4,NaN,0.425687,0.202145,1.0,-2191.0,0.0,1.0,NaN,0.051266,1.0,...,0.0,NaN,NaN,NaN,0.000000e+00,0.00,1.0,24463.710,NaN,4